name: Installer CI

on:
  push:
    tags:
      - "**"
  pull_request:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ">1.18.0"
      - name: Build application
        shell: pwsh
        run: .\app.ps1
      - name: Build installer
        shell: pwsh
        run: makensis "app.nsi"
      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: gh release create --title "Release ${{ github.ref_name }}" "${{ github.ref_name }}" "app-installer.exe"

